# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli
# MI, if no schema provided, default to public schema for Postgresql

[print_schema]
file = "src/schema.rs"
schema = "ore"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "./migrations"
